### ISSUE TITLE
Barometric vent

### ISSUE THREAD

**Issue by ToreBj** [ian-dee/RileyLink-Water-Resistant-Wireless-Charging-Case#1]
I can't see the barometric vent in the BOM. Neither is there any opening for one in the STL file?

**Comment by ian-dee** [comment]
HI Tore, correct. There is no B-Vent in the open source version of the case, since the vent itself is not an off the shelf component and would be impossible for others to order at a low minimum order quantity. The case will work without a B Vent, but will hold air pressure that needs to be burped out as the cap is put on. For the mass production variant I opted to add a B-Vent so the cap can easily be put on without burping air, and to keep the pressure equalized to the environment when traveling on airplanes, changing elevation, etc.

**Comment by ToreBj** [comment]
👍 Thanks for what looks like a new and very useful option. I'm doing what I can for my local community providing them with 3D printed stuff for free. The tough case has been very popular lately. Take care in these Corona times 😁

**Comment by ian-dee** [comment]
Thats great! Please note - I am planning to upload the common case design that supports both medtronic & Omnipod versions of the RileyLink. The version that is up now is great for Omnipod, but is a very tight fit for the Medtronic. I'll upload today - will be Rev C
